id = "kanagawa-nvim-theme"
name = "Kanagawa.nvim"
version = "0.2.0"
schema_version = 1
authors = [
    "Ethan Gilmore <ethanmckgilmore@gmail.com>",
    "Yair Chan <enyaoficial001@gmail.com>",
    "Brad Purchase <bradpurchase@gmail.com>",
]
description = "Faithful Zed port of rebelot's Kanagawa.nvim theme"
repository = "https://github.com/bradpurchase/zed-kanagawa"
